# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/inference.proto\x12\tinference\"8\n\x11TranscribeRequest\x12\x13\n\x0b\x61udio_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06target\x18\x02 \x01(\t\"\"\n\tASRResult\x12\x15\n\rtranscription\x18\x01 \x01(\t\"\x94\x01\n\x12TranscribeResponse\x12\x39\n\x06result\x18\x01 \x03(\x0b\x32).inference.TranscribeResponse.ResultEntry\x1a\x43\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.inference.ASRResult:\x02\x38\x01\x32\x61\n\x12\x41SRInferenceServer\x12K\n\ntranscribe\x12\x1c.inference.TranscribeRequest\x1a\x1d.inference.TranscribeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBERESPONSE_RESULTENTRY']._loaded_options = None
  _globals['_TRANSCRIBERESPONSE_RESULTENTRY']._serialized_options = b'8\001'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=36
  _globals['_TRANSCRIBEREQUEST']._serialized_end=92
  _globals['_ASRRESULT']._serialized_start=94
  _globals['_ASRRESULT']._serialized_end=128
  _globals['_TRANSCRIBERESPONSE']._serialized_start=131
  _globals['_TRANSCRIBERESPONSE']._serialized_end=279
  _globals['_TRANSCRIBERESPONSE_RESULTENTRY']._serialized_start=212
  _globals['_TRANSCRIBERESPONSE_RESULTENTRY']._serialized_end=279
  _globals['_ASRINFERENCESERVER']._serialized_start=281
  _globals['_ASRINFERENCESERVER']._serialized_end=378
# @@protoc_insertion_point(module_scope)
