apiVersion: v1
kind: Secret
metadata:
  name: argo-server-sso-secret
  namespace: argo-workflows
type: Opaque
data:
  # FIXME: Replace the following values with your own
  client-id: <base64-encoded-client-id>
  client-secret: <base64-encoded-client-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-sa.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: developer-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: business-sa.service-account-token
  namespace: argo-workflows
  annotations:
    kubernetes.io/service-account.name: business-sa
type: kubernetes.io/service-account-token
