# 実行用SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sa
  namespace: argo-workflows
  # 先ほどterraformで作成したargo workflows用のサービスアカウントのEmail
  annotations:
    iam.gke.io/gcp-service-account: "your-gcp-service-account-email"
---
# DeveloperのSSO用SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: argo-workflows
  # FIXME: Replace the following value with your own
  annotations:
    workflows.argoproj.io/rbac-rule: "email == 'your-google-email-1'"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
# BusinessのSSO用SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-sa
  namespace: argo-workflows
  # FIXME: Replace the following value with your own
  annotations:
    workflows.argoproj.io/rbac-rule: "email == 'your-google-email-2'"
    workflows.argoproj.io/rbac-rule-precedence: "1"
