apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-cpu
spec:
  template:
    spec:
      containers:
        - name: chat-app
          image: asia-northeast1-docker.pkg.dev/<project-id>/chat-app/chat-app:latest
          command:
            [
              ".venv/bin/python",
              "-m",
              "uvicorn",
              "src.main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "8000",
            ]
          resources:
            requests:
              cpu: 1000m
              memory: 8000Mi
            limits:
              cpu: 1400m
              memory: 10000Mi
