services:
  fastapi-docker-debugger:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/app/.venv/bin/python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    container_name: fastapi-docker-debugger
    ports:
      - "8000:8000"
      - "5678:5678"
    expose:
      - "5678"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
