[project]
name = "fastapi-docker-debugger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "debugpy>=1.8.9",
    "fastapi>=0.115.5",
    "uvicorn>=0.32.1",
]
