apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pubsub-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: train-workflow-dependency
      eventSourceName: gcp-pubsub
      eventName: train-workflow-trigger # eventSourceに合わせている
  triggers:
    - template:
        name: train-workflow-template
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: train-workflow-
                namespace: argo
              spec:
                serviceAccountName: argo-workflows-sa
                workflowTemplateRef:
                  name: train-workflow
                arguments:
                  parameters:
                  - name: config
                    valueFrom:
                      path: /event  # イベントデータを引数に設定
          parameters:
            - src:
                dependencyName: train-workflow-dependency
                dataKey: body
              dest: spec.arguments.parameters.0.value
