apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
  namespace: argo
spec:
  entrypoint: hello

  templates:
    - name: hello
      steps:
        - - name: hello
            template: print-message
            arguments:
              parameters: [{ name: message, value: "hello1" }]

    - name: print-message
      inputs:
        parameters:
          - name: message
      container:
        image: busybox
        command: [echo]
        args: ["{{inputs.parameters.message}}"]

      metrics:
        prometheus:
          - name: workflow_duration
            help: duration of current workflow
            labels:
              - key: template_name
                value: sample-workflow
            gauge:
              value: "{{workflow.duration}}"
          - name: workflow_result
            help: result of workflow executed lastly
            labels:
              - key: template_name
                value: summary-workflow
              - key: status
                value: "{{workflow.status}}"
            gauge:
              value: "1"
