apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  argo-workflows-workflow-controller
  namespace:  argo
spec:
  replicas:  1
  selector:
    matchLabels:
      app.kubernetes.io/name:  argo-workflows-workflow-controller
      app.kubernetes.io/instance:  argo-workflows
  template:
    metadata:
      annotations:
        ad.datadoghq.com/controller.checks:  |
          {
              "openmetrics": {
              "init_config": {},
              "instances": [
                  {
                  "openmetrics_endpoint": "http://%%host%%:9090/metrics",
                  "namespace": "argo-workflows",
                  "metrics": ["argo_workflows_*"],
                  }
              ]
              }
          }
    spec:
      serviceAccountName:  argo-workflows-workflow-controller
      containers:
        -  name:  controller
