[project]
name = "datadog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddtrace>=2.20.0",
    "google-generativeai>=0.8.4",
    "openai>=1.60.1",
    "python-dotenv>=1.0.1",
]
