name: Run creating docker image and deploy to app runner.

on:
  push:
    branches: [main]

jobs:
  gcp:
    name: Deploy to App Runner.

    env:
      SERVICE_NAME: your-service-name
      REPOSITORY_NAME: your-repository-name
      REGION: ap-northeast-1
      DOCKERFILE: docker/Dockerfile

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - id: 'auth'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $REGION

      - name: Authorize Docker
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR.
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f $DOCKERFILE .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to App Runner
        run: |-
          aws apprunner update-service \
            --service-name $SERVICE_NAME \
            --source-configuration imageRepository={imageIdentifier=$ECR_REGISTRY/$ECR_REPOSITORY:latest}
