apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - managedcertificate.yaml

patches:
  - path: deployment.yaml
  - path: ingress.yaml
  - path: configmap.yaml
