name: Run creating docker image and deploy to app runner.

on:
  push:
    branches: [main]

jobs:
  gcp:
    name: Deploy to App Runner.

    env:
      # FIXME: Set your own repository name
      ECR_REPOSITORY: sample-aws-ecr-repository
      REGION: ap-northeast-1
      DOCKERFILE: docker/Dockerfile

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - id: 'auth'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - name: Authorize Docker
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR.
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f $DOCKERFILE .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
