name: Run creating docker image and deploy to azure container apps

on:
  push:
    branches: [feature/azure-cicd]

jobs:
  azure:
    name: Deploy to Container Apps.

    env:
      # FIXME: Replace with your own values
      CONTAINER_REGISTRY: sampleazurecontainerregistryhoshii
      AZURE_CONTAINER_REGISTRY: sampleazurecontainerregistryhoshii.azurecr.io
      REPOSITORY_NAME: sample-azure-repository
      CONTAINER_APPS_NAME: sample-azure-container-app
      RESOURCE_GROUP: sample-azure-resource-group
      DOCKERFILE: docker/Dockerfile

    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - id: Auth
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Authorize Docker
        run: az acr login -n $CONTAINER_REGISTRY --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$REPOSITORY_NAME:latest -f $DOCKERFILE .
          docker push $AZURE_CONTAINER_REGISTRY/$REPOSITORY_NAME:latest

      - name: Deploy to Container Apps
        run: |
          az containerapp update \
            -n $CONTAINER_APPS_NAME \
            -g $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY/$REPOSITORY_NAME:latest
