apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      env: local
resources:
  - ../../base
  - ../../overlays/local/argo-workflows/extract.yaml
  - ../../overlays/local/argo-workflows/transform.yaml
  - ../../overlays/local/argo-workflows/train.yaml
  - ../../overlays/local/argo-workflows/workflow.yaml
  - ../../overlays/local/secret-store.yaml

patches:
  - path: external-secret.yaml
  - path: workflow.yaml
  - path: argo-events/event-source.yaml
